### ISSUE TITLE
Hidden fields

### ISSUE THREAD

**Issue by ghost** [chrissainty/FluentValidationWithRazorComponents#1]
This is not issue, but just wondering how should I add hidden fields, like having an Id for example.

**Comment by chrissainty** [comment]
Hey, just wondering why you'd want to add a hidden field?

**Comment by ghost** [comment]
See, I opened this issue originally because I had a view-model with some properties having validation and another I didn't need to. When submitting the `EditForm` I was receiving an error, and I though I need that property to be added as hidden field, like I used to do with MVC. I was thinking maybe FluentValidation require all properties in the view-model need to be add it to the form. However, the error turned out to be something else, and I realize no hidden fields were needed. Thank you for answering anyway.
