### ISSUE TITLE
Errors with FluentValidation 9.0.1

### ISSUE THREAD

**Issue by mkopara** [chrissainty/FluentValidationWithRazorComponents#2]
When I try to build this solution I get two errors in your file EditContextFluentValidationExtensions.cs

var validationResults = validator.Validate(editContext.Model);
Error	CS1503	Argument 1: cannot convert from 'object' to 'FluentValidation.IValidationContext'

var context = new ValidationContext(fieldIdentifier.Model, new PropertyChain(), new MemberNameValidatorSelector(properties));
Error	CS0305	Using the generic type 'ValidationContext<T>' requires 1 type argument

Could this be outdated or incompatible with FluentValidation 9.x?

**Comment by chrissainty** [comment]
Hi this repo is extremely out of date. Please refer to the [Blazored FluentValidation repo](https://github.com/Blazored/FluentValidation) for an up to date production library.
