### ISSUE TITLE
Update for DotNet 5.0

### ISSUE THREAD

**Issue by genifycom** [chrissainty/FluentValidationWithRazorComponents#4]
Hi Chris,

Under DotNet 5.0 there are two compiler errors:

var validationResults = validator.Validate(editContext.Model);

Gives Error	CS1503	Argument 1: cannot convert from 'object' to 'FluentValidation.IValidationContext'

var context = new ValidationContext(fieldIdentifier.Model, new PropertyChain(), new MemberNameValidatorSelector(properties));

Gives Error	CS0305	Using the generic type 'ValidationContext<T>' requires 1 type arguments

Do you know how to fix?

Thanks

**Comment by chrissainty** [comment]
Hi @genifycom. This code is really old now. If you're intested in using Fluent Validation with Blazor I'd suggest you checkout [Blazored FluentValidation](https://github.com/Blazored/FluentValidation). I made it after I wrote this blog post.

**Comment by genifycom** [comment]
Awesome. Thanks Chris
